### ISSUE TITLE
Add datatype exports for Grid features

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-react#18]
At the moment the feature array is a simple array of objects, however, we could add property checks by making it an array of objects that is from a list of types exported by the API exporter. 

This should be researched for applicability and developed.

**Comment by ChronosSF** [comment]
Looks possible using the following definition:

```Javascript
features: React.PropTypes.arrayOf(
    React.PropTypes.oneOfType([
        React.PropTypes.shape($.ig.react.propTypes.shapes.igGridSelection),
        React.PropTypes.shape($.ig.react.propTypes.shapes.igGridUpdating)
    ])
)
```
We just need to extract the shape definitions from the features API docs and determine a way to recognize widgets that are grid features (igGrid*) looks promising and there is probably a way to extend shapes for igTreeGrid* features.

**Comment by ChronosSF** [comment]
Unfortunately the default error creation is pretty helpless for this scenario. If I add Filtering in the same sample which is not defined as a possible shape for features I get:

react.js:3631 Warning: Failed prop type: Invalid prop `features[2]` supplied to `<<anonymous>>`.
    in Unknown (created by App)
    in App

And if I put a wrong prop for an existing property of the Updating shape I get the same:

react.js:3631 Warning: Failed prop type: Invalid prop `features[1]` supplied to `<<anonymous>>`.
    in Unknown (created by App)
    in App

This may be worth an issue on its own since custom errors are supported. Will update later.

**Comment by kdinev** [comment]
Removing the research label, because the research is done.

**Comment by ChronosSF** [comment]
After discussing this with @kdinev  we decided to drop this. The gain is fairly marginal at the cost of massively inflating the size of the code that is getting referenced. In fact, we should probably think about getting rid of the type defs for the minified files entirely as the release version of React does not perform any type checks anyway. By default only the unminified React would do them.
