### ISSUE TITLE
Edit error validation message moves above the grid if you click other cells.

### ISSUE THREAD

**Issue by agoldenbaum** [IgniteUI/igniteui-react#34]
**Steps to Reproduce**
1. Run the following sample: https://www.infragistics.com/react-demos/samples/grids/data-grid/cell-editing
2. Enter edit mode on the "City" column and delete the value.
3. Try to leave edit mode. The validation message "Error, cell is empty" should show.
4. Click on other cells below the one you are in edit mode on.

**Result**
The error message moves above the grid.

**Expected Result**
The error message should not move

**Comment by ig-robstoffers** [comment]
This issue has been resolved in our latest version.
