### ISSUE TITLE
igniteui-react-grids: shadow remains after dropdown closes

### ISSUE THREAD

**Issue by rwieruch** [IgniteUI/igniteui-react#4]
We are using `igniteui-react-grids` in version `^16.13.0`.

When we open a modal with a data grid, hit the ... [0 ]button to open up the dropdown of the grid, hit the "Cancel" button of the dropdown, everything is fine.

However, when we open the same modal with the data grid, hit the ... [0] button to open up the dropdown again, and close the modal instead of the dropdown, both (modal and dropdown) disappear, however, the parent element of the dropdown stays with a drop shadow while the actual dropdown element disappears. [1]

In other words, when the dropdown gets unmounted implicitly because it was attached to another unmounting component (here modal), it keeps it wrapping element around.

This may be related to https://github.com/IgniteUI/igniteui-angular/issues/7133

-----

[0]

<img width="621" alt="Screenshot 2021-11-11 at 22 25 31" src="https://user-images.githubusercontent.com/2479967/141371342-319d3660-6faf-4cc8-85e2-4d5587f57d85.png">

[1]

<img width="1277" alt="Screenshot 2021-11-11 at 22 23 42" src="https://user-images.githubusercontent.com/2479967/141371612-9522186c-ac4b-4e27-902a-b9228c993d66.png">
<img width="1248" alt="Screenshot 2021-11-11 at 22 22 09" src="https://user-images.githubusercontent.com/2479967/141371619-9fcff12b-e325-43ca-9621-95cd18920428.png">

**Comment by mddifilippo89** [comment]
This issue is fixed in other platforms, such as WebComponents. But in React we don't get access to the life cycle events to trap when this happens so I would avoid deleting things in the Dev tools specifically. The issue should never be happening in normal use.

**Comment by rwieruch** [comment]
I'd say it's still an issue, because for us the shadow still appears in the case described above (closing the modal while the dropdown is open). We are not deleting the element from the dev tools as stated by @mddifilippo89. Anyway, we will not bother too much about it and continue our work.
