### ISSUE TITLE
IgrGrid & IgrSelect - The drop-down list of the IgrSelect appears under the Row Edit Overlay of the IgrGrid

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-react#54]
## Description  

When the user implemented and ran a React web app that has the `IgrGrid` which enabled row editing and customized with the cell edit template including the `IgrSelect`, the drop-down list of the `IgrSelect` was overlapped by the row edit overlay only if the number of rows of the grid was less than 3. It worked as expected if the number of rows equals or exceeds 3.

(This issue comes from the Ignite UI for WebComponents. See also: https://github.com/IgniteUI/igniteui-webcomponents/issues/1076 )

## Steps to reproduce  

1. Run the sample React app I attached to this issue.
2. The web page will have a grid component with 3 rows.
3. Delete 1 row in that grid component using the action strip.
4. Enter row edit mode by double-clicking any cells.
5. the second column in edit mode shows a selection component.
6. Click the drop-down button of that selection component.

## Result  
The drop-down list of the `IgrSelect` appeared under the Row Edit Overlay of the `IgrGrid`.

## Expected result  
The drop-down list of the `IgrSelect` should always appear in front of the Row Edit Overlay of the `IgrGrid`, whatever the number of rows is.

## Attachments  

https://github.com/IgniteUI/igniteui-webcomponents/assets/102948935/9cc5dfd1-33ff-4d12-8cc7-cb1e2cc26fe3

[📦c-00235378-react-app1.zip](https://github.com/IgniteUI/igniteui-react/files/14369929/c-00235378-react-app1.zip)

**Comment by damyanpetev** [comment]
Closing in favor of the Web Components issue that will be automatically included in React once resolved.
