### ISSUE TITLE
import IgGrid from 'igniteui-react';

### ISSUE THREAD

**Issue by MonkeyJumps** [IgniteUI/igniteui-react#84]
import igGrid from 'igniteui-react' 
does not build. neither does
 import {igGrid} from 'igniteui-react'

**Comment by ChronosSF** [comment]
Could you please share your sample app?

**Comment by MonkeyJumps** [comment]
I installed using the following npm install igniteui-react --save

My project.json is updated
 "igniteui-react": "^1.1.0-PreRelease.1",

I use the following import statement
import igGrid from 'igniteui-react';

then I run my build script and i receive the following error:
Module not found: Error: Can't resolve 'igniteui-react' in

**Comment by ChronosSF** [comment]
Could you please try using this instead:
```javascript
import igGrid from "igniteui-react/ui/igGrid.js"
```
Components had to be split in different so they can be imported correctly. They can all bel found under ignite-ui/ui .

**Comment by ChronosSF** [comment]
Please, reopen the issue if you have any issues with the suggested solution.
