### ISSUE TITLE
Is this free or paid?

### ISSUE THREAD

**Issue by mraak** [IgniteUI/igniteui-react#94]
I'm confused, I see you're selling this on your main website but from github obviously I can take it and use for free?

**Comment by kdinev** [comment]
@mraak The repository contains the react extensions for Ignite UI, but the main product and its functionality is obtained from our website: https://www.infragistics.com/products/ignite-ui

You would notice in the [Build](https://github.com/IgniteUI/igniteui-react#build) description there is a reference to our private npm feed, which you need a license to obtain the `ignite-ui-full` package from. 

You can get a free trial of Ignite UI on our website. Once you decide whether you want to use it in your applications, you can purchase a license.
